### ISSUE TITLE
Magnifier does not work in IE.

### ISSUE THREAD

**Issue by Vondry** [samuelmeuli/react-magnifier#13]
Magnifier does not transpile JavaScript Classes which are [not supported](https://caniuse.com/#search=ES6%20Class) in IE.

Workaround based on [this issue](https://github.com/webpack/webpack/issues/2031#issuecomment-219040479) in webpack configuration:
```
  {
          test: /.../,
          exclude: /node_modules\/(?!react-magnifier).*,
          use: [...],
  }            
```

Please transpile Classes down to functions, thank you.

**Comment by samuelmeuli** [comment]
Fixed in `v3.0.4`.
