### ISSUE TITLE
Support for base64 image

### ISSUE THREAD

**Issue by weslei-dias-vakt** [samuelmeuli/react-magnifier#15]
I'm trying to use this library in my base64 images, but when i hover the image i only have an grey square instead of a zoom.
This is my code
`<Magnifier src={data:image/png;base64,${page.images[0]}} mgShape="square" />
`
Any ideas?

**Comment by samuelmeuli** [comment]
It's working for me, see [this new story](https://react-magnifier.samuelmeuli.com/?path=/story/magnifier--base64-image).

Would you be willing to share the image that's not working?

**Comment by weslei-dias-vakt** [comment]
Sure @samuelmeuli,

This is the behaviour that i have.

![image](https://user-images.githubusercontent.com/57624369/75327940-1bdb5b80-5875-11ea-8ec7-68d9be44dbfe.png)

I'm doing something wrong? My library version is 3.0.4

**Comment by samuelmeuli** [comment]
I mean could you share the image source?

Maybe it's a problem related to newline characters, see [this SO question](https://stackoverflow.com/a/28288424/6767508).

**Comment by weslei-dias-vakt** [comment]
Sure,

[base64-source.log](https://github.com/samuelmeuli/react-magnifier/files/4254510/base64-source.log)

I will try this solution related with the SO

**Comment by samuelmeuli** [comment]
Applying `.replace(/(\r\n|\n|\r)/gm, "")` fixed it for me. Please me know whether it's working for you, too.

**Comment by weslei-dias-vakt** [comment]
The problem was related with the SO. Thanks for the suggestion @samuelmeuli , now its working.
