### ISSUE TITLE
supporting <picture>

### ISSUE THREAD

**Issue by vladimir-fsh** [samuelmeuli/react-magnifier#4]
Hey. Great library. Thank you. I've used in my project and good to have to support of `<picture>` tag. Like `renderImage={this.renderIImage} `and I can use `<picture>` inside.

**Comment by samuelmeuli** [comment]
Hi @vladimir-fsh, thanks for the suggestion.

In what situation would `<picture>` support help? I can't imagine the library being used on an image with art direction. If it's for responsive images, would adding support for the `srcset` and `sizes` attributes on the `<img>` tag work as well?

**Comment by vladimir-fsh** [comment]
@samuelmeuli Hi. I guess `srcset` and `sizes` would be also good. Thanks

**Comment by samuelmeuli** [comment]
Ok, great :) I've added this in v2.1. You can now pass any props to the magnifier (including `srcSet` and `sizes`) and they will be applied to the `<img>` element.
