### ISSUE TITLE
it's not working properly when I have multiple images with carousel

### ISSUE THREAD

**Issue by makasanas** [samuelmeuli/react-magnifier#5]
So in this case it's work fine if I scroll or resize window. But without that it's not working fine. Also when scroll window it's showing me error when I have multiple images. 

`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null`

**Comment by makasanas** [comment]
Hi Samuel,

Thanks for you response. it's only solve that error issue. But still in carousel problem is that image changing position without moving scroll or resize so in that case it's not working properly. Because new image coordinates change so some how I need to call this function again. 

`this.calcImgBoundsDebounced`

**Comment by samuelmeuli** [comment]
Hi @makasanas,

Thanks for reporting this, I think I understand now. It might make sense to recalculate the image bounds whenever the mouse enters the image instead. I'll have a go at this later this week.

Could you tell me what carousel component you're using so I can test this with your setup?

**Comment by samuelmeuli** [comment]
This should be fixed now. Please let me know if it still doesn't work.
