### ISSUE TITLE
missing context binding for onTouchStart callback

### ISSUE THREAD

**Issue by auto1bagrat** [samuelmeuli/react-magnifier#8]
Hello.

Thanks for the library!

I found a minor bug. The code is lacking context binding for onTouchStart. I think the line number 88 will be the perfect place for this one :)

```
    this.onTouchStart = this.onTouchStart.bind(this);
```

I can open a PR if you like.

**Comment by samuelmeuli** [comment]
Hey @auto1bagrat, thanks for opening the issue! You're right, that line is missing. I'd gladly accept a PR :)
